from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name="index"),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('delete_item/', views.delete_item, name='delete_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('place_order/', views.place_order, name='place_order'),
    path('buy-now/', views.buy_now, name='buy_now'),
    path('shop-details/', views.shopDetail, name='shopDetail'),
    path('search/', views.product_search, name='product_search'),
    path('get_cart_count/', views.get_cart_count, name='get_cart_count'),
    path('category/<int:category_id>/', views.category_products, name='category_products'),
            # admin urls
    path('admin-applianceuganda',views.admin1,name="admin-applianceuganda"),
    path('create/', views.create_product, name='create_product'),
    path('get_brands/', views.get_brands, name='get_brands'),
    path('product-list/', views.productList, name='productList'),
    path('category-list/', views.categoryList, name='categoryList'),
    path('brand-list/', views.brandList, name='brandList'),
    path('delete-product', views.delete_product, name='delete_product'),
    path('delete-category', views.delete_category, name='delete_category'),
    path('delete-brand', views.delete_brand, name='delete_brand'),
    path('delete-order', views.delete_order, name='delete_order'),
    path('add-category/', views.add_category, name='add-category'),
    path('add-brand/', views.add_brand, name='add-brand'),
    path('orders/', views.order_list, name='order_list'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('edit-product/<int:product_id>/', views.edit_product, name='edit_product'),
  ]