# Generated by Django 5.0.2 on 2024-02-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='media/slides')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
    ]
