# Generated by Django 5.0.2 on 2024-02-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_product_category_alter_product_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
