# Generated by Django 5.0.2 on 2024-02-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
