# Generated by Django 5.0.2 on 2024-03-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
