# Generated by Django 5.0.2 on 2024-03-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
